### ISSUE TITLE
sub data output

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/assignR#1]
Update subOrigData so output can be read directly into calRaster w/o additional modification (i.e. have it return a spatial points dataframe w correct format and same projection info as the world d2H isoscape)

**Comment by Demerara** [comment]
The present function works this way. The additional modification in some of the help pages like assginR.Rd is to delete some outliers.

**Comment by bumbanian** [comment]
OK, thanks my mistake.

In this case, can we update the help and rmd to use a less clunky approach to remove the outliers:

dd = d[d@coords[,1] < -80,]

Then no typecasting back and forth between spatial point df and df is needed

**Comment by Demerara** [comment]
Good idea! The help pages and Rmd have been updated accordingly.
