### ISSUE TITLE
Package dependencies

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/assignR#11]
Only import specific functions needed.

**Comment by Demerara** [comment]
Done. 
Replaced "import" with "importFrom" in NAMESPACE and replaced "Depends" with "Imports" in DESCRIPTION.

**Comment by Demerara** [comment]
Failed building the package after changing the NAMESPACE and DESCRIPTION. I am working on solving it.

**Comment by Demerara** [comment]
The problem is the interaction between the NAMESPACE, DESCRIPTION and the vignettes file (assignR.Rmd). Because we changed the DESCRIPTION and NAMESPACE, the raster and sp package will not be loaded automatically when load the assignR. We need to load raster and sp in the Rmd file for the functions in raster and sp or it will failed the building package.

**Comment by bumbanian** [comment]
Let me look at the changes. The package should load all of the functions on which it depends… The user shouldn’t have to do this

Sent from my iPhone

On Mar 28, 2020, at 12:48 PM, Chao Ma <notifications@github.com> wrote:

﻿

The problem is the interaction between the NAMESPACE, DESCRIPTION and the vignettes file (assignR.Rmd). Because we changed the DESCRIPTION and NAMESPACE, the raster and sp package will not be loaded automatically when load the assignR. We need to load raster and sp in the Rmd file for the functions in raster and sp or it will failed the building package.

**Comment by Demerara** [comment]
Because now we are using Imports instead of Depends in DESCRIPTION, raster, sp, maptools are not loaded automatically. The functions in examples of help pages and Rmd that require these packages will not run and cause R CMD check errors. Thus loading necessary packages in the examples and Rmd is needed.

**Comment by bumbanian** [comment]
I don’t think this is quite right. I believe the problem is that I’ve used explicit function calls for non-base functions, eg sp::spTransform(), to ensure that the code is safe to ambiguous names. The AE is asking us to use a different approach to the same thing - using imports. But imported packages and their functions are not loaded in a separate top-level environment. Instead they are loaded in the ‘imports’ environment of the assignR package. I haven’t been able to find documentation that says this explicitly, but my guess is that because so::spTransform() is looking for the function within the app package, it fails if that package is not loaded into its own environment. The functions should still be there, just that R can’t find them. 

So let’s remove all package names from the function calls and try it.

**Comment by Demerara** [comment]
Let me create two branches and compare.

**Comment by Demerara** [comment]
I imported all the necessary functions from other packages to avoid :: in our package (see branch imports-and-no-libray-in-example-and-no-in-function"). Building package is successful but can not pass devtools::check() cause the imported packages can not be called in the example. For example in the example of help page of "states":
> data("states")
> plot(states)
Error will be found here in devtools::check(). But adding library(raster) will solve the error.

Necessary packages are attached in the help pages of branch "imports-and-use-library()-in-example-and-use-in-functions". It passed both devtools::build() and devtools::check(). It passed in building of Travis CI too.
