### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/assignR#13]
"The Github repository at the moment does not include any tests. If you are unfamiliar with tests, you can read more about them here: http://r-pkgs.had.co.nz/tests.html. In general, they help ensure your code does what you want it to do. The `testthat` packages has made great steps to make this easier. I would also encourage you to consider evaluating the code coverage of your tests using something like codecov (https://docs.codecov.io/docs/quick-start), which can also be publicised on your Github repo. This helps you and others see how much of your code is covered by the tests you have written and is becoming standard in best practice software development."

**Comment by Demerara** [comment]
Testthat and codecov added. Right now, the code coverage  of test is 94%.
