### ISSUE TITLE
oddsRatio returns NaN

### ISSUE THREAD

**Issue by jjsarancha** [SPATIAL-Lab/assignR#31]
oddsRatio function returns:
"$`P1/P2 odds ratio`
  a   b   c   d   e 
NaN NaN NaN NaN NaN 

$`Ratio of numbers of cells in two polygons`
[1] 1.862384"

Original function:
 "...if (nlayers(pdR) > 1) {
      extrVals.p1 = colSums(extrVals[[1]])
      extrVals.p2 = colSums(extrVals[[2]])
    }
    else {
      extrVals.p1 = sum(extrVals[[1]])
      extrVals.p2 = sum(extrVals[[2]])..."

Edit function to remove missing values:

"...if (nlayers(pdR) > 1) {
      extrVals.p1 = colSums(extrVals[[1]],na.rm=TRUE)
      extrVals.p2 = colSums(extrVals[[2]],na.rm=TRUE)
    }
    else {
      extrVals.p1 = sum(extrVals[[1]],na.rm=TRUE)
      extrVals.p2 = sum(extrVals[[2]],na.rm=TRUE)..."

**Comment by bumbanian** [comment]
Thanks! Fixed in 3bad922
