### ISSUE TITLE
refTrans

### ISSUE THREAD

**Issue by eunjng** [SPATIAL-Lab/assignR#41]
If exchangeable hydrogen was corrected by 3-point linear calibration using three different standard materials, 
Which Calibration of hstds should I use?

For example, my samples were corrected by USGS43, USGS CBS, and USGS KHS. so I can use US_H_6 and also EC_H_9. 
Is there any method that can add both or another alternative resolution?

**Comment by bumbanian** [comment]
All calibrations are currently anchored by 2 standards. This could be added in a future release but for now would recommend using the 2-point calibration that spans the widest range (or the most relevant range for your unknown samples) of delta values.

**Comment by eunjng** [comment]
Thanks for your answer! 👍
