### ISSUE TITLE
Ref_scale in subOrigData

### ISSUE THREAD

**Issue by eunjng** [SPATIAL-Lab/assignR#43]
Hi :D
My data's Calibration method is "EC_H_9", and what I want to use in subOrigData has the "OldEC.1_H_1" as Calibration. 
I can see that subOrigData's default ref_scale is "VSMOW_H" and in data("stds"), "EC_H_9" also have the same ref_scale, "VSMOW_H".
Then, is it right that I don't need the procedure of 'refTrans' in my data? 

Now I have error to access "CRAN" and I'm not sure about that, so I want to ask you about it.

Thanks!

**Comment by bumbanian** [comment]
Yes, unless you override the default arguments subOrigData() will automatically apply refTrans() to the data and return data on the VSMOW_H reference scale, which should be comparable to your own data. 

I'd need more info to address the error you report accessing CRAN.

**Comment by eunjng** [comment]
Thanks!

I thought I need the additional procedure of 'refTrans' after using subOrigData(), because the reference data was used "OldEC.1_H_1". 
As you tell me, my unknown samples were based on "VSMOW_H" so I think I don't need to use 'refTrans' anymore.
