### ISSUE TITLE
The package can add Global Network of Isotopes in Rivers (GNIR) dataset？

### ISSUE THREAD

**Issue by Otoliths** [SPATIAL-Lab/assignR#5]
Hi,
    In addition to the Global Network for Isotopes in Precipitation(GNIP) dataset，the package can add Global Network of Isotopes in Rivers (GNIR) dataset？

**Comment by bumbanian** [comment]
Thanks for the suggestion. The package can take any raster isoscape (isotope map) as input. The precipitation isoscapes included as data objects are from waterisotopes.org (http://wateriso.utah.edu/waterisotopes/pages/data_access/ArcGrids.html) you will also find river isoscapes for the contiguous USA there which could be loaded and used by the assignR package. River isoscapes for other regions could be used in the same way, but as far as I know do currently exist and would have be be created first.
