### ISSUE TITLE
Update range map reference

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/assignR#8]
On a related note, I was looking quickly through the assignR reference manual on CRAN and noticed that it cites Natureserve as the source for the Mountain Plover shapefile.  If you click through the links, Natureserve no longer has maps, as it has merged with BirdLife International.  https://www.natureserve.org/conservation-tools/digital-distribution-maps-birds-western-hemisphere  So I am not sure if we need to update that citation?

**Comment by Demerara** [comment]
Check this out: http://datazone.birdlife.org/species/factsheet/mountain-plover-charadrius-montanus
This is the link that Hannah shared with me with the plover range data. We can update the link with this. @bumbanian

**Comment by bumbanian** [comment]
removed files
